### ISSUE TITLE
New sentences

### ISSUE THREAD

**Issue by JeanPiquemal** [borekon/logipole-translation#1]
sentences added since the last commit:

1=Make a copy of the original files
2=Selected Files
3=Metadata++ initializing Exiftool
4=Metadata++ is a free software (freeware), no restrictions of use apply.\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY.\nIf you have any questions, please check the Logipole Forums first.
5=Include traffic information
6=Color Selection
7=Include Sub Folders
8=Move Files
9=Copy Files
10=Destination Folder
11=Output folder structure
12=Get GPS metadata from  a file
13=Automatically backup original when modifying
14=Where to backup?
15=To a sub-folder (<folder name>\\Sav)
16=To the Metadata++ private folder (user\\AppData\\Local\\Metadata++\\Sav)"
17=To this folder
18=Rename as
19=Refresh
20=Close tab
21=Copy folder path
22=Copy file path
23=Import ICC profile from a file
24=Import ICC profile from a .icc file

**Comment by borekon** [comment]
Should i add it as ther are here or with special sintaxis?

**Comment by JeanPiquemal** [comment]
Hi
It’s OK like that, it’s simpler for you without the syntax i suppose.
Jean

**Comment by borekon** [comment]
I'll add it as separated file
